name: lanenet
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=21.2.2
  - python=3.8.12
  - setuptools=58.0.4
  - sqlite=3.36.0
  - wheel=0.37.0
  - pip:
    - glog==0.3.1
    - loguru==0.2.5
    - tensorflow_gpu==2.5.3
    - tqdm==4.28.1
    - matplotlib==2.2.5
    - opencv_contrib_python==4.2.0.32
    - numpy>=1.19.2
    - scikit_learn==0.24.1
    - tensorflow==2.5.3
    - PyYAML==5.4.1
